name: "POC: Deploy Existing Docs to Cloudflare"

permissions:
  contents: read
  deployments: write


on:
  workflow_dispatch:

jobs:
  deploy-existing-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Built Docs Branch
        uses: actions/checkout@v4
        with:
          ref: 'versioned-gh-pages'

      - name: Remove .git folder
        run: rm -rf .git

      - name: Remove unused previews to reduce file count
        run: |
          echo "Deleting old PR previews..."
          rm -rf previews/
          
          echo "Remaining file count:"
          find . -type f | wc -l

      - name: Force delete all oversized files
        run: |
          echo "Finding and deleting files over 24MB..."
          find . -type f -size +24M -delete
          echo "Oversized files destroyed."
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # The '.' means deploy the current directory (the root of the checked-out branch)
          # Make sure to update 'hugo-docs-poc' to your actual Cloudflare project name!
          command: pages deploy . --project-name=toolbox-docs --branch=main
