name: "Cloudflare PR Preview"

permissions:
  contents: read
  deployments: write # Required for Cloudflare to post the preview link to the PR

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/**'
      - '.hugo/**'

jobs:
  build-and-preview:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: .hugo
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.145.0"
          extended: true

      - name: Build Hugo site
        run: hugo --minify
        env:
          HUGO_BASEURL: "/"
          HUGO_RELATIVEURLS: false

      - name: Create Staging Directory
        run: |
          mkdir staging
          mv public staging/dev
          # Ignore the releases.releases file for the PR preview to keep it simple

      - name: Remove oversized files
        run: find staging/ -type f -size +24M -delete
          
      - name: Deploy PR Preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy staging --project-name=toolbox-docs --branch=${{ github.head_ref }}
