name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Add this step
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # This tells the action where to find your configuration
          config-file: .github/release-please-config.yml